[monophone_training]
train_dir = "train"
iteration = 4
tolerance = 1e-1
convergence = 1e-4
component_per_state = 9
enable = true

[predict]
predict_dir = "predict"
beam_size = 40
real_time = false
enable = true

[storage]
monophone_modele_file = "monophone.json"
phonemes_file = "phonemes.json"
log_prob_bigram_file = "log-prob-bigram.json"
